# Define the full name of the taxonomic ranks
RANKS = {
    'stateofmatter': { 'en': 'State of matter', 'fr': 'État de la matière' },
    'kingdom': { 'en': 'Kingdom', 'fr': 'Règne' },
    'phylum': { 'en': 'Phylum', 'fr': 'Phylum' },
    'subphylum': { 'en': 'Subphylum', 'fr': 'Sous-phylum' },
    'superclass': { 'en': 'Superclass', 'fr': 'Super-classe' },
    'class': { 'en': 'Class', 'fr': 'Classe' },
    'subclass': { 'en': 'Subclass', 'fr': 'Sous-classe' },
    'infraclass': { 'en': 'Infraclass', 'fr': 'Classe interne' },
    'subterclass': { 'en': 'Subterclass', 'fr': 'Sous-classe interne' },
    'superorder': { 'en': 'Superorder', 'fr': 'Super-ordre' },
    'order': { 'en': 'Order', 'fr': 'Ordre' },
    'suborder': { 'en': 'Suborder', 'fr': 'Sous-ordre' },
    'infraorder': { 'en': 'Infraorder', 'fr': 'Infra-ordre' },
    'parvorder': { 'en': 'Parvorder', 'fr': 'Micro-ordre' },
    'zoosection': { 'en': 'Zoosection', 'fr': 'Section animale' },
    'zoosubsection': { 'en': 'Zoosubsection', 'fr': 'Sous-section animale' },
    'superfamily': { 'en': 'Superfamily', 'fr': 'Super-famille' },
    'epifamily': { 'en': 'Epifamily', 'fr': 'Épifamille' },
    'family': { 'en': 'Family', 'fr': 'Famille' },
    'subfamily': { 'en': 'Subfamily', 'fr': 'Sous-famille' },
    'supertribe': { 'en': 'Supertribe', 'fr': 'Super-tribu' },
    'tribe': { 'en': 'Tribe', 'fr': 'Tribu' },
    'subtribe': { 'en': 'Subtribe', 'fr': 'Sous-tribu' },
    'genus': { 'en': 'genus', 'fr': 'Genre' },
    'genushybrid': { 'en': 'Genushybrid', 'fr': 'Genre hybride' },
    'subgenus': { 'en': 'Subgenus', 'fr': 'Sous-genre' },
    'section': { 'en': 'Section', 'fr': 'Section' },
    'subsection': { 'en': 'Subsection', 'fr': 'Sous-section' },
    'complex': { 'en': 'Complex', 'fr': 'Complexe' },
    'species': { 'en': 'Species', 'fr': 'Espèce' },
    'hybrid': { 'en': 'Hybrid', 'fr': 'Hybride' },
    'subspecies': { 'en': 'Subspecies', 'fr': 'Sous-espèce' },
    'infrahybrid': { 'en': 'Infrahybrid', 'fr': 'Infra-hybride' },
    'variety': { 'en': 'Variety', 'fr': 'Variété' },
    'form': { 'en': 'Form', 'fr': 'Forme' }, 
}

# Define the full names of IUCN redlist statuses
IUCN = {
    'EX': { 'en': 'Extinct', 'fr': 'Éteinte' },
    'EW': { 'en': 'Extinct in the wild', 'fr': "Éteinte à l'état sauvage" },
    'CR': { 'en': 'Critically endangered', 'fr': "En danger critique d'extinction" },
    'EN': { 'en': 'Endangered', 'fr': 'En danger' },
    'VU': { 'en': 'Vulnerable', 'fr': 'Vulnérable' },
    'NT': { 'en': 'Near threatened', 'fr': 'Quasi menacée' },
    'CD': { 'en': 'Conservation dependent', 'fr': 'Dépendente de la conservation' },
    'LC': { 'en': 'Least concern', 'fr': 'Préoccupation mineure' },
    'DD': { 'en': 'Data deficient', 'fr': 'Données insuffisantes' },
    'NE': { 'en': 'Not evaluated', 'fr': 'Non-évaluée' },
}