# Here are languages options, this must be reflected on texts
languages:
  current: fr
  available: [ fr, en ]
# Interface parameters
interface:
  cartography:
    range:
      transition:
        display: 200
        center: 500
      color: 'rgba(200, 110, 100, 0.7)'
      padding: 20
# Text in different languages
texts:
  description:
    vernaculars:
      en: 'Vernacular names:'
      fr: 'Noms vernaculaires :'