interface:
  title: Phyloscope
  cartography:
    maxzoom: 6
    range:
      color: rgba(200, 110, 100, 0.7)
      padding: 20
      transition:
        center: 500
        display: 200
languages:
  available:
  - fr
  - en
  current: fr
taxonomy:
  current: 3
texts:
  description:
    vernaculars:
      en: 'Vernacular names:'
      fr: 'Noms vernaculaires :'
