interface:
  cartography:
    maxzoom: 6
    start:
      center: [0, 0]
      zoom: 1
    range:
      opacity: 0.7
      padding: 20
      transition:
        center: 500
        display: 200
  title: Phyloscope
  transition: 200
languages:
  available:
  - fr
  - en
  current: fr
texts:
  vernaculars:
    en: 'Other names:'
    fr: 'Autres noms :'
taxonomy:
  current: 3000
typesorting:
  - 'stateofmatter'
  - 'kingdom'
  - 'phylum'
  - 'subphylum'
  - 'superclass'
  - 'class'
  - 'subclass'
  - 'infraclass'
  - 'subterclass'
  - 'superorder'
  - 'order'
  - 'suborder'
  - 'infraorder'
  - 'parvorder'
  - 'zoosection'
  - 'zoosubsection'
  - 'superfamily'
  - 'epifamily'
  - 'family'
  - 'subfamily'
  - 'supertribe'
  - 'tribe'
  - 'subtribe'
  - 'genus'
  - 'genushybrid'
  - 'subgenus'
  - 'section'
  - 'subsection'
  - 'complex'
  - 'species'
  - 'hybrid'
  - 'subspecies'
  - 'infrahybrid'
  - 'variety'
  - 'form'