interface:
  title: Phyloscope
  transition: 200
  cartography:
    maxzoom: 6
    start:
      center: [0, 0]
      zoom: 2
    range:
      opacity: 0.7
      padding: 20
      transition:
        center: 500
        display: 200
    baselayers:
      - name:
          en: Natural Earth 1
          fr: Natural Earth 1
        url: ne1
        style: dark
      - name:
          en: Natural Earth 2
          fr: Natural Earth 2
        url: ne2
        style: dark
      - name:
          en: Hypsometric Tints
          fr: Teintes hypsométriques
        url: hypso
        style: dark
      - name:
          en: Greyscale
          fr: Niveau de gris
        url: grey
        style: light
languages:
  available:
    fr:
      locale: fr-FR
      name: Français
    en:
      locale: en-GB
      name: English
  current: fr
taxonomy:
  current: 3616
photography:
  url: https://inaturalist-open-data.s3.amazonaws.com/photos/
typesorting:
  stateofmatter:
    level: 100
    en: State of matter
    fr: État de la matière
  kingdom:
    level: 90
    en: Kingdom
    fr: Règne
  phylum:
    level: 80
    en: Phylum
    fr: Phylum
  subphylum:
    level: 78
    en: Subphylum
    fr: Sous-phylum
  superclass:
    level: 75
    en: Superclass
    fr: Super-classe
  class:
    level: 70
    en: Class
    fr: Classe
  subclass:
    level: 68
    en: Subclass
    fr: Sous-classe
  infraclass:
    level: 65
    en: Infraclass
    fr: Classe interne
  subterclass:
    level: 64
    en: Subterclass
    fr: Sous-classe interne
  superorder:
    level: 62
    en: Superorder
    fr: Super-ordre
  order:
    level: 60
    en: Order
    fr: Ordre
  suborder:
    level: 58
    en: Suborder
    fr: Sous-ordre
  infraorder:
    level: 57
    en: Infraorder
    fr: Infra-ordre
  parvorder:
    level: 56
    en: Parvorder
    fr: Micro-ordre
  zoosection:
    level: 50
    en: Zoosection
    fr: Section animale
  zoosubsection:
    level: 48
    en: Zoosubsection
    fr: Sous-section animale
  superfamily:
    level: 44
    en: Superfamily
    fr: Super-famille
  epifamily:
    level: 42
    en: Epifamily
    fr: Épifamille
  family:
    level: 40
    en: Family
    fr: Famille
  subfamily:
    level: 36
    en: Subfamily
    fr: Sous-famille
  supertribe:
    level: 34
    en: Supertribe
    fr: Super-tribu
  tribe:
    level: 30
    en: Tribe
    fr: Tribu
  subtribe:
    level: 25
    en: Subtribe
    fr: Sous-tribu
  genus:
    level: 20
    en: Genus
    fr: Genre
  genushybrid:
    level: 18
    en: Genushybrid
    fr: Genre hybride
  subgenus:
    level: 17
    en: Subgenus
    fr: Sous-genre
  section:
    level: 15
    en: Section
    fr: Section
  subsection:
    level: 14
    en: Subsection
    fr: Sous-section
  complex:
    level: 12
    en: Complex
    fr: Complexe
  species:
    level: 10
    en: Species
    fr: Espèce
  hybrid:
    level: 8
    en: Hybrid
    fr: Hybride
  subspecies:
    level: 7
    en: Subspecies
    fr: Sous-espèce
  variety:
    level: 5
    en: Variety
    fr: Variété
  form:
    level: 4
    en: Form
    fr: Forme
  infrahybrid:
    level: 2
    en: Infrahybrid
    fr: Infra-hybride
iucn:
  EX:
    en: Extinct
    fr: Éteinte
  EW:
    en: Extinct in the wild
    fr: Éteinte à l'état sauvage
  CR:
    en: Critically endangered
    fr: En danger critique d'extinction
  EN:
    en: Endangered
    fr: En danger
  VU:
    en: Vulnerable
    fr: Vulnérable
  NT:
    en: Near threatened
    fr: Quasi menacée
  CD:
    en: Conservation dependent
    fr: Dépendente de la conservation
  LC:
    en: Least concern
    fr: Préoccupation mineure
  DD:
    en: Data deficient
    fr: Données insuffisantes
  NE:
    en: Not evaluated
    fr: Non-évaluée
texts:
  vernaculars:
    en: 'Other names:'
    fr: 'Autres noms :'
  database:
    update:
      en: 'Updated on '
      fr: 'Actualisé le '
    initialization:
      en: 'Initialized on '
      fr: 'Initialisé le '
  help:
    cartography:
      tutorial:
        title:
            en: Using the map
            fr: Utilisation de la carte
        content:
          basemap:
            fr: Changer le fond de carte
            en: Change the basemap
          overlay:
            fr: Ajouter une couche avec des toponymes
            en: Add an overlay with toponyms
          range:
            fr: Afficher ou cacher la zone de répartition du taxon
            en: Display or hide the taxon's range extent
          center:
            fr: Centrer la carte sur la zone de répartition du taxon
            en: Center the map on the taxon's range extent
      source:
        title:
          en: Data source
          fr: Source des données
        content:
          - type: ul
            text:
              fr: >
                Les données géographiques de répartition des espèces sont issues de la base
                <a href='https://www.inaturalist.org/pages/range_maps' target='_blank'>iNaturalist Open Range Map Dataset.</a>
                Cette base de données est générée à partir du
                <a href='https://www.inaturalist.org/blog/84677-introducing-the-inaturalist-geomodel' target='_blank'>Geomodel iNaturalist</a>
                utilisant l'apprentissage profond pour créer des zones de présence potentielle en fonction des observations et du relief.
              en: >
                Geographical data on species ranges are taken from the
                <a href='https://www.inaturalist.org/pages/range_maps' target='_blank'>iNaturalist Open Range Map Dataset.</a>
                This database is generated from the <a href='https://www.inaturalist.org/blog/84677-introducing-the-inaturalist-geomodel' target='_blank'>Geomodel iNaturalist</a>
                that uses a deep learning model to create areas of potential presence based on observations and terrain relief.
            content:
              - en: >
                  The base iNaturalist dataset being generated mostly at the species rank level, range areas of the upper ranks of the taxonomy are the result of the
                  aggregation of range areas of the lower ranks.
                fr: >
                  Les données de base étant générées majoritairement au niveau des espèces par iNaturalist, les zones répartition des rangs supérieurs de
                  la taxonomie résultent de l'agrégation des zones de répartition des rangs inférieurs.
              - en: >
                  Range areas have been reconnected at the antimeridian (180<sup>th</sup> meridian, in the Pacific Ocean) because the base iNaturalist dataset
                  is discontinuous when crossing this line. This operation is performed by a personal algorithm available on the
                  <a href='https://github.com/jberli/phyloscope' target='_blank'>project repository</a>, and it enables a better centering of the map view.
                  Those areas are then smoothed using a gaussian smoothing algorithm to obtain a more organic edge instead of the hexagonal cells generated by
                  the iNaturalist model.
                fr: >
                  Les zones de répartition sont également reconnectées au niveau de l'antiméridien (180<sup>ème</sup> méridien, dans l'océan Pacifique)
                  car les données de base sont discontinues lorsqu'elles traversent cette ligne. Cette opération est effectuée par un algorithme personnel disponible sur le
                  <a href='https://github.com/jberli/phyloscope' target='_blank'>dépôt du projet</a>, elle permet de center la carte de manière optimale.
                  Les zones sont ensuite lissées par un algorithme de lissage gaussien afin d'obtenir des bordures plus organiques par rapport aux
                  cellules hexagonales générées par le modèle iNaturalist.
          - type: ul
            text:
              fr: >
                Les fonds de carte proviennent de <a href='https://www.naturalearthdata.com/downloads/10m-raster-data/' target='_blank'>Natural Earth</a>,
                et plus spécifiquement la version 6.0 qui propose une nouvelle version avec une meilleure résolution et disponible
                <a href='https://shadedrelief.com/ne-draft/' target='_blank'>ici.</a> Les différents fonds de carte disponibles sont :
              en: >
                Geographical species range data 
            content:
              - en: >
                  <b>Natural Earth 1</b> represents the land use and is derived from satellite images.
                fr: >
                  <b>Natural Earth 1</b> représente l'occupation des sols dérivée de l'imagerie satellite.
              - en: >
                  <b>Natural Earth 2</b> is derived from Natural Earth 1 and represents an idealized Earth, with little human influence.
                fr: >
                  <b>Natural Earth 2</b> est dérivé de Natural Earth 1 et représente la Terre de manière idéalisée, avec peu d'influence humaine.
              - en: >
                  <b>Hypsometric tints</b> is a mix of shaded relief and colours based on elevation and climate.
                fr: >
                  <b>Teintes hypsométriques</b> propose un mélange entre un ombrage du relief et des couleurs basées sur l'élévation et le climat.
              - en: >
                  <b>Greyscale</b> is a shaded relief in grey levels.
                fr: >
                  <b>Niveau de gris</b> est un ombrage du relief en niveau de gris.
    taxonomy:
      en: ''
      fr: ''
    statistics:
      en: ''
      fr: ''