interface:
  title: Phyloscope
  transition: 200
  cartography:
    maxzoom: 6
    start:
      center: [0, 0]
      zoom: 2
    range:
      opacity: 0.7
      padding: 20
      transition:
        center: 500
        display: 200
    baselayers:
      - name:
          en: Natural Earth 1
          fr: Natural Earth 1
        url: ne1
        style: dark
      - name:
          en: Natural Earth 2
          fr: Natural Earth 2
        url: ne2
        style: dark
      - name:
          en: Hypsometric Tints
          fr: Teintes hypsométriques
        url: hypso
        style: dark
      - name:
          en: Greyscale
          fr: Niveau de gris
        url: grey
        style: light
languages:
  available:
    fr:
      locale: fr-FR
      name: Français
    en:
      locale: en-GB
      name: English
  current: fr
taxonomy:
  current: 3616
photography:
  url: https://inaturalist-open-data.s3.amazonaws.com/photos/
typesorting:
  stateofmatter:
    level: 100
    en: State of matter
    fr: État de la matière
  kingdom:
    level: 90
    en: Kingdom
    fr: Règne
  phylum:
    level: 80
    en: Phylum
    fr: Phylum
  subphylum:
    level: 78
    en: Subphylum
    fr: Sous-phylum
  superclass:
    level: 75
    en: Superclass
    fr: Super-classe
  class:
    level: 70
    en: Class
    fr: Classe
  subclass:
    level: 68
    en: Subclass
    fr: Sous-classe
  infraclass:
    level: 65
    en: Infraclass
    fr: Classe interne
  subterclass:
    level: 64
    en: Subterclass
    fr: Sous-classe interne
  superorder:
    level: 62
    en: Superorder
    fr: Super-ordre
  order:
    level: 60
    en: Order
    fr: Ordre
  suborder:
    level: 58
    en: Suborder
    fr: Sous-ordre
  infraorder:
    level: 57
    en: Infraorder
    fr: Infra-ordre
  parvorder:
    level: 56
    en: Parvorder
    fr: Micro-ordre
  zoosection:
    level: 50
    en: Zoosection
    fr: Section animale
  zoosubsection:
    level: 48
    en: Zoosubsection
    fr: Sous-section animale
  superfamily:
    level: 44
    en: Superfamily
    fr: Super-famille
  epifamily:
    level: 42
    en: Epifamily
    fr: Épifamille
  family:
    level: 40
    en: Family
    fr: Famille
  subfamily:
    level: 36
    en: Subfamily
    fr: Sous-famille
  supertribe:
    level: 34
    en: Supertribe
    fr: Super-tribu
  tribe:
    level: 30
    en: Tribe
    fr: Tribu
  subtribe:
    level: 25
    en: Subtribe
    fr: Sous-tribu
  genus:
    level: 20
    en: Genus
    fr: Genre
  genushybrid:
    level: 18
    en: Genushybrid
    fr: Genre hybride
  subgenus:
    level: 17
    en: Subgenus
    fr: Sous-genre
  section:
    level: 15
    en: Section
    fr: Section
  subsection:
    level: 14
    en: Subsection
    fr: Sous-section
  complex:
    level: 12
    en: Complex
    fr: Complexe
  species:
    level: 10
    en: Species
    fr: Espèce
  hybrid:
    level: 8
    en: Hybrid
    fr: Hybride
  subspecies:
    level: 7
    en: Subspecies
    fr: Sous-espèce
  variety:
    level: 5
    en: Variety
    fr: Variété
  form:
    level: 4
    en: Form
    fr: Forme
  infrahybrid:
    level: 2
    en: Infrahybrid
    fr: Infra-hybride
iucn:
  EX:
    en: Extinct
    fr: Éteinte
  EW:
    en: Extinct in the wild
    fr: Éteinte à l'état sauvage
  CR:
    en: Critically endangered
    fr: En danger critique d'extinction
  EN:
    en: Endangered
    fr: En danger
  VU:
    en: Vulnerable
    fr: Vulnérable
  NT:
    en: Near threatened
    fr: Quasi menacée
  CD:
    en: Conservation dependent
    fr: Dépendente de la conservation
  LC:
    en: Least concern
    fr: Préoccupation mineure
  DD:
    en: Data deficient
    fr: Données insuffisantes
  NE:
    en: Not evaluated
    fr: Non-évaluée
texts:
  vernaculars:
    en: 'Other names:'
    fr: 'Autres noms :'
  database:
    update:
      en: 'Updated on '
      fr: 'Actualisé le '
    initialization:
      en: 'Initialized on '
      fr: 'Initialisé le '
  help:
    cartography:
      - type: title
        en: Using the map
        fr: Utilisation de la carte
      - type: buttons
        content:
          - type: standard
            text:
              en: Natural Earth 1
              fr: Natural Earth 1
            label:
              en: Change the basemap
              fr: Changer le fond de carte
          - type: standard
            text:
              en: Physical
              fr: Physique
            label:
              en: Add an overlay with toponyms
              fr: Ajouter une couche avec des toponymes
          - type: slider
            label:
              en: Display or hide the taxon's range extent
              fr: Afficher ou cacher la zone de répartition du taxon
          - type: vector
            svg: center            
            label:
              en: Center the map on the taxon's range extent
              fr: Centrer la carte sur la zone de répartition du taxon
      - type: title
        en: Data source
        fr: Source des données
      - type: paragraph
        content:
          en: >
            Geographical data on species ranges are taken from the
            <a href='https://www.inaturalist.org/pages/range_maps' target='_blank'>iNaturalist Open Range Map Dataset.</a>
            This database is generated from the <a href='https://www.inaturalist.org/blog/84677-introducing-the-inaturalist-geomodel' target='_blank'>Geomodel iNaturalist</a>
            that uses a deep learning model to create areas of potential presence based on observations and terrain relief.
          fr: >
            Les données géographiques de répartition des espèces sont issues de la base
            <a href='https://www.inaturalist.org/pages/range_maps' target='_blank'>iNaturalist Open Range Map Dataset.</a>
            Cette base de données est générée à partir du
            <a href='https://www.inaturalist.org/blog/84677-introducing-the-inaturalist-geomodel' target='_blank'>Geomodel iNaturalist</a>
            utilisant l'apprentissage profond pour créer des zones de présence potentielle en fonction des observations et du relief.
      - type: list
        sorted: false
        content:
          - en: >
              The base iNaturalist dataset being generated mostly at the species rank level, range areas of the upper ranks of the taxonomy are the result of the
              aggregation of range areas of the lower ranks.
            fr: >
              Les données de base étant générées majoritairement au niveau des espèces par iNaturalist, les zones répartition des rangs supérieurs de
              la taxonomie résultent de l'agrégation des zones de répartition des rangs inférieurs.
          - en: >
              Range areas have been reconnected at the antimeridian (180<sup>th</sup> meridian, in the Pacific Ocean) because the base iNaturalist dataset
              is discontinuous when crossing this line. This operation is performed by a personal algorithm available on the
              <a href='https://github.com/jberli/phyloscope' target='_blank'>project repository</a>, and it enables a better centering of the map view.
              Those areas are then smoothed using a gaussian smoothing algorithm to obtain a more organic edge instead of the hexagonal cells generated by
              the iNaturalist model.
            fr: >
              Les zones de répartition sont également reconnectées au niveau de l'antiméridien (180<sup>ème</sup> méridien, dans l'océan Pacifique)
              car les données de base sont discontinues lorsqu'elles traversent cette ligne. Cette opération est effectuée par un algorithme personnel disponible sur le
              <a href='https://github.com/jberli/phyloscope' target='_blank'>dépôt du projet</a>, elle permet de center la carte de manière optimale.
              Les zones sont ensuite lissées par un algorithme de lissage gaussien afin d'obtenir des bordures plus organiques par rapport aux
              cellules hexagonales générées par le modèle iNaturalist.
      - type: paragraph
        content:
          en: >
            Geographical species range data
          fr: >
            Les fonds de carte proviennent de <a href='https://www.naturalearthdata.com/downloads/10m-raster-data/' target='_blank'>Natural Earth</a>,
            et plus spécifiquement la version <a href='https://shadedrelief.com/ne-draft/' target='_blank'>6.0</a>
            qui propose une meilleure résolution. Les différents fonds de carte disponibles sont :
      - type: list
        sorted: false
        content:
          - en: >
              <b>Natural Earth 1</b> represents the land use and is derived from satellite images.
            fr: >
              <b>Natural Earth 1</b> représente l'occupation des sols dérivée de l'imagerie satellite.
          - en: >
              <b>Natural Earth 2</b> is derived from Natural Earth 1 and represents an idealized Earth, with little human influence.
            fr: >
              <b>Natural Earth 2</b> est dérivé de Natural Earth 1 et représente la Terre de manière idéalisée, avec peu d'influence humaine.
          - en: >
              <b>Hypsometric tints</b> is a mix of shaded relief and colours based on elevation and climate.
            fr: >
              <b>Teintes hypsométriques</b> propose un mélange entre un ombrage du relief et des couleurs basées sur l'élévation et le climat.
          - en: >
              <b>Greyscale</b> is a shaded relief in grey levels.
            fr: >
              <b>Niveau de gris</b> est un ombrage du relief en niveau de gris.
    taxonomy:
      - type: title
        en: Navigating the taxonomy
        fr: Navigation dans la taxonomie
      - type: paragraph
        content:
          en: >
            Geographical species range data
          fr: >
            La vue taxonomique est une représentation de l'arbre du vivant. Afin de faciliter sa compréhension,
            les explications qui suivent utilisent un analogie avec la famille (ancêtres, parents, enfants, <i>etc.</i>).
            Un code couleur arbitraire est utilisé pour représenter les différents niveaux de la taxonomie.
      - type: taxonomy
        ancestry:
          - en: Life
            fr: Vie
          - en: Grandparent
            fr: Grand-parent
          - en: Parent
            fr: Parent
        parent:
          en: Parent
          fr: Parent
        siblings:
          - en: Previous taxon
            fr: Taxon précédent
          - en: Active taxon
            fr: Taxon actif
          - en: Next taxon
            fr: Taxon suivant
        children:
          - en: Previous child
            fr: Enfant précédent
          - en: Child
            fr: Enfant
          - en: Next child
            fr: Enfant suivant
        label:
          en: >
          fr: >
            Figure 1 : Schématisation de la vue taxonomique du Phyloscope
      - type: list
        sorted: false
        content:
          - en: >
            fr: >
              Tout en haut, la liste des <b>ancêtres</b> du taxon actif sont visibles de la racine (la vie) jusqu'au parent du taxon actif.
              Il est possible de cliquer sur chaque ancêtre pour l'activer.
          - en: >
            fr: >
              Le niveau supérieur comporte le <b>parent</b> du taxon actif. Cliquer dessus remonte la taxonomie et le parent devient le taxon actif.
          - en: >
            fr: >
              Le niveau intermédiaire comporte le <b>taxon actif</b> ainsi que ses frères (<i>i.e.</i> les autres enfants du parent du taxon actif).
              Cliquer dessus ou utiliser la molette de la souris permet de changer le taxon actif pour le frère suivant ou précédent. Ce niveau est
              classé par le nombre de taxon contenu dans chaque taxon de gauche à droite.
          - en: >
            fr: >
              Le niveau inférieur comporte les <b>enfants</b> du taxon actif. Cliquer sur l'enfant situé au centre descend l'enfant devient le taxon actif.
              Cliquer sur un des deux autres enfant ou utiliser la molette permet de naviguer dans les enfants du taxon actif. Ce niveau est également
              classé par le nombre de taxon contenu dans chaque enfant de gauche à droite.
      - type: colorscale
        placeholder:
          en: Hover on a color
          fr: Passer le cursor sur une color
        level:
          en: level
          fr: niveau
        label:
          en: >
          fr: >
            Figure 2 : Les couleurs utilisées pour représenter les niveaux de la taxonomie
      - type: title
        en: What is phylogenetics?
        fr: Qu'est-ce que la phylogénétique ?
      - type: paragraph
        content:
          en: >
            Geographical species range data
          fr: >
            Le terme taxonomie renvoie à une manière de classifier et de catégoriser des données, généralement sous forme d'une hiérarchie. Un élément de
            cet arbre taxonomique est appelé taxon (ou taxa au pluriel). Pour représenter la diversité de la vie, les scientifiques utilisent la
            <a href='https://fr.wikipedia.org/wiki/Taxonomie' target='_blank'>taxonomie</a> pour représenter la relation entre les espèces, on appelle ça un
            <a href='https://fr.wikipedia.org/wiki/Arbre_phylog%C3%A9n%C3%A9tique' target='_blank'>arbre phylogénétique</a>. Cette relation reflète
            <a href='https://fr.wikipedia.org/wiki/Histoire_%C3%A9volutive_du_vivant' target='_blank'>l'histoire évolutive</a> partagées par ces espèces.
            Un taxon de cette taxonomie désigne alors n'importe quel niveau de cet arbre, par exemple une
            <a href='https://fr.wikipedia.org/wiki/Esp%C3%A8ce' target='_blank'>espèce</a> (<i>e.g.</i> Columba palumbus), une
            <a href='https://fr.wikipedia.org/wiki/Classe_(biologie)' target='_blank'>classe</a> (<i>e.g.</i> les oiseaux) ou encore la
            <a href='https://fr.wikipedia.org/wiki/Vie' target='_blank'>vie</a> elle-même.
      - type: paragraph
        content:
          en: >
            Geographical species range data
          fr: >
            L'arbre phylogénétique utilisé ici provient de la base de données collaborative <a href='https://www.inaturalist.org/' target='_blank'>iNaturalist</a>.
            Cette base de données utilise la <a href='https://fr.wikipedia.org/wiki/Cladistique' target='_blank'>cladistique</a> comme principe sous-jacent. La cladistique
            est une approche de la classification biologique dans laquelle les organismes sont catégorisés en groupes basés sur l'hypothèse du
            <a href='https://fr.wikipedia.org/wiki/Dernier_anc%C3%AAtre_commun' target='_blank'>denier ancêtre commun</a> (<i>cf.</i> Figure 3). Ces groupes, appelés
            <a href='https://fr.wikipedia.org/wiki/Clade' target='_blank'>clades</a>, doivent être
            <a href='https://fr.wikipedia.org/wiki/Monophylie' target='_blank'>monophylétique</a>, c'est-à-dire qu'ils doivent contenir tous les taxa ayant
            évolués à partir du dernier ancêtre commun à l'ensemble du groupe. À partir de cette logique, certains groupes comme les vers ou les poissons
            n'existent pas car ils contiennent une telle diversité d'espèces qu'il faudrait y inclure les humains.
      - type: vector
        svg: phylogenetic
        label:
          en: >
          fr: >
            Figure 3 : Représentation classique d'un clade en phylogénétique
      - type: paragraph
        content:
          en: >
            Geographical species range data
          fr: >
            Cet arbre phylogénétique est une simplification de l'arbre phylogénétique du vivant. Il s'agit d'une réduction du nombre
            de taxon intermédiaire en sélectionnant les taxa les plus représentatifs. Cette sélection peut être un héritage de l'histoire
            de la biologie de l'évolution, mais il s'agit souvent de refléter la <a href='https://fr.wikipedia.org/wiki/Sp%C3%A9ciation' target='_blank'>spéciation</a>
            induite par différents facteurs : les mouvements tectoniques (isolation des espèces, activité volcanique), les
            modifications anthropiques d'un milieu, <i>etc.</i>).
      - type: paragraph
        content:
          en: >
            Geographical species range data
          fr: >
            Prenons par exemple trois ordres : les <a href='https://fr.wikipedia.org/wiki/Columbiformes' target='_blank'>columbiformes</a> (pigeons et tourterelles),
            les <a href='https://fr.wikipedia.org/wiki/Pterocliformes' target='_blank'>pterocliformes</a> (gangas et syrrhaptes) et les
            <a href='https://fr.wikipedia.org/wiki/Cuculiformes' target='_blank'>cuculiformes</a> (coucous et apparentés).
            Dans notre base de données simplifiées, ces trois ordres appartiennent directement à la classe des oiseaux.
            Mais en réalité, les columbiformes et les pterocliformes sont plus proches entre eux qu'ils ne le sont des cuculiformes et cette information n'est pas
            présente dans notre base. Ces trois ordres appartiennent au clade des columbaves, comme le montre la Figure 4.
      - type: vector
        svg: aves
        label:
          en: >
          fr: >
            Figure 4 : Représentation du clade Columbaves
      - type: paragraph
        content:
          en: >
            Geographical species range data
          fr: >
            La recherche sur la génétique ne cesse d'avancer et certains taxons sont susceptibles de changer lorsque de nouvelles découvertes
            émergent. Phyloscope est mis-à-jour chaque mois, et la base est complètement réinitialisée une fois par an.
            Cette réinitialisation reconstruit entièrement la taxonomie et permet de supprimer les taxa qui n'existent plus et d'ajouter des nouveaux.
    statistics:
      en: ''
      fr: ''